FROM python:3.12-slim-bookworm
LABEL program="Program 1"
LABEL description="CSIT OCT 2024 MINI CHALLENGE"
LABEL author="alexlogy"
LABEL github="https://github.com/alexlogy/"

# Environment Variables
ENV API_URL="https://u8whitimu7.execute-api.ap-southeast-1.amazonaws.com/prod"
ENV OUTPUT_DIR="/data/output/"
ENV CLEAN_DIR="/data/cleaned/"
ENV VALIDATED_DIR="/data/validated/"

# Set working directory to /app
WORKDIR /app

# Copy the code into the image
COPY ../program_one /app

# Installing Python Dependencies
RUN mkdir -p /data && pip install -r requirements.txt

# Entrypoint
ENTRYPOINT ["python", "main.py"]