FROM python:3.12-slim-bookworm
LABEL program="Program 2"
LABEL description="CSIT OCT 2024 MINI CHALLENGE"
LABEL author="alexlogy"
LABEL github="https://github.com/alexlogy/"

# Environment Variables
ENV API_URL="https://u8whitimu7.execute-api.ap-southeast-1.amazonaws.com/prod"
ENV OUTPUT_DIR="/workspace/"

# Set working directory to /workspace
WORKDIR /workspace

# Copy the code into the image
COPY ../program_two /workspace

# Installing Python Dependencies
RUN pip install -r requirements.txt

# Entrypoint
ENTRYPOINT ["python", "main.py"]